version: 2.1

var_1: &cache_key v1-{{ checksum "package.json" }}

var_2: &restore_cache
  restore_cache:
    key: *cache_key

var_3: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - node_modules

var_4: &attach_workspace
  attach_workspace:
    at: .

orbs:
  aws-cli: circleci/aws-cli@0.1.13

executors:
  node:
    docker:
      - image: circleci/node:12.4.0

jobs:
  prepare:
    executor: node
    steps:
      - checkout
      - *restore_cache
      - run: yarn install
      - *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  deploy:
    parameters:
      deploy_env:
        type: string
      env_prefix:
        type: string
    executor: node
    steps:
      - checkout
      - *attach_workspace
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Install aws-amplify CLI
          command: sudo yarn global add @aws-amplify/cli
      - run:
          name: Checkout Amplify << parameters.deploy_env >> environment
          command: amplify init --amplify "{\"envName\":\"<< parameters.deploy_env >>\",\"defaultEditor\":\"code\"}" --providers "{\"awscloudformation\":{\"useProfile\":true,\"profileName\":\"default\"}}"
      - run:
          name: Inject secrets
          command: |
            # undo deletion of googleAppIdUserPool and googleAppSecretUserPool
            git reset --hard
            # inject secrets
            sed -i "s/<< parameters.deploy_env >>-google-auth-secret-here/$<< parameters.env_prefix >>_GOOGLE_AUTH_SECRET/g" amplify/team-provider-info.json
      - run:
          name: Deploy to << parameters.deploy_env >>
          command: amplify publish --invalidateCloudFront --codegen "{\"generateCode\":false}" --yes

workflows:
  build_deploy:
    jobs:
      - prepare
      - deploy:
          name: deploy staging
          context: aws-profile
          deploy_env: staging
          env_prefix: STAGING
          requires:
            - prepare
          filters:
            branches:
              only:
                - develop
      - deploy:
          name: deploy prod
          context: aws-profile
          deploy_env: production
          env_prefix: PRODUCTION
          requires:
            - prepare
          filters:
            branches:
              only:
                - master
